//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_tables.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int billid { get; set; }
        public string ordername { get; set; }
        public Nullable<int> orderid { get; set; }
        public string username { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
