//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data_tables.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int SalesID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
